services:
  # SAB Lanyard MongoDB Database
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - amdstore_network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # SAB Lanyard MinIO Object Storage
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - minio_data:/data
    networks:
      - amdstore_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # SAB Lanyard Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    pull_policy: always
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${BACKEND_PORT:-5000}
      BASE_URL: ${BACKEND_URL:-http://localhost}
      MONGODB_URI: ${MONGODB_URI:-mongodb://amdadmin:password123@mongodb:27017/minipreorder?authSource=admin}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-sab@fit.hcmus.edu.vn}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-amdadmin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-amdadmin123}
      APPSCRIPT_URL: ${APPSCRIPT_URL:-your-appscript-url-here}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio}
      MINIO_PORT: ${MINIO_PORT:-9000}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-amdstore}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    expose:
      - "5000"
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
      minio:
        condition: service_healthy
        restart: true
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - amdstore_network

  # SAB Lanyard Frontend React App (with Nginx Reverse Proxy)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${REACT_APP_API_URL:-http://localhost}
    pull_policy: always
    environment:
      VITE_API_URL: ${REACT_APP_API_URL:-http://localhost}
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      backend:
        condition: service_started
    networks:
      - amdstore_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data:
  minio_data:
  backend_uploads:


networks:
  amdstore_network:
  domain_network:
    external: true
    name: multi-domain
