const ERROR_CODES = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	NOT_FOUND: 'NOT_FOUND',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	CONFLICT: 'CONFLICT',
	DATABASE_ERROR: 'DATABASE_ERROR',
	EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	BAD_REQUEST: 'BAD_REQUEST',
	PAYMENT_ERROR: 'PAYMENT_ERROR',
	FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
	PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
	ORDER_PROCESSING_ERROR: 'ORDER_PROCESSING_ERROR',
	COMBO_ERROR: 'COMBO_ERROR',
	AUTH_ERROR: 'AUTH_ERROR',
	RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
	CORS_ERROR: 'CORS_ERROR'
};

const ERROR_MESSAGES = {
	[ERROR_CODES.VALIDATION_ERROR]: {
		vi: 'Dữ liệu không hợp lệ',
		en: 'Validation failed'
	},
	[ERROR_CODES.NOT_FOUND]: {
		vi: 'Không tìm thấy tài nguyên',
		en: 'Resource not found'
	},
	[ERROR_CODES.UNAUTHORIZED]: {
		vi: 'Chưa xác thực',
		en: 'Unauthorized'
	},
	[ERROR_CODES.FORBIDDEN]: {
		vi: 'Không có quyền truy cập',
		en: 'Forbidden'
	},
	[ERROR_CODES.CONFLICT]: {
		vi: 'Dữ liệu bị xung đột',
		en: 'Resource conflict'
	},
	[ERROR_CODES.DATABASE_ERROR]: {
		vi: 'Lỗi cơ sở dữ liệu',
		en: 'Database error'
	},
	[ERROR_CODES.EXTERNAL_SERVICE_ERROR]: {
		vi: 'Lỗi dịch vụ bên ngoài',
		en: 'External service error'
	},
	[ERROR_CODES.INTERNAL_SERVER_ERROR]: {
		vi: 'Lỗi máy chủ nội bộ',
		en: 'Internal server error'
	},
	[ERROR_CODES.BAD_REQUEST]: {
		vi: 'Yêu cầu không hợp lệ',
		en: 'Bad request'
	},
	[ERROR_CODES.PAYMENT_ERROR]: {
		vi: 'Lỗi xử lý thanh toán',
		en: 'Payment processing error'
	},
	[ERROR_CODES.FILE_UPLOAD_ERROR]: {
		vi: 'Lỗi tải file lên',
		en: 'File upload error'
	},
	[ERROR_CODES.PRODUCT_UNAVAILABLE]: {
		vi: 'Sản phẩm không khả dụng',
		en: 'Product unavailable'
	},
	[ERROR_CODES.ORDER_PROCESSING_ERROR]: {
		vi: 'Lỗi xử lý đơn hàng',
		en: 'Order processing error'
	},
	[ERROR_CODES.COMBO_ERROR]: {
		vi: 'Lỗi xử lý combo',
		en: 'Combo processing error'
	},
	[ERROR_CODES.AUTH_ERROR]: {
		vi: 'Lỗi xác thực',
		en: 'Authentication error'
	},
	[ERROR_CODES.RATE_LIMIT_ERROR]: {
		vi: 'Vượt quá giới hạn yêu cầu',
		en: 'Rate limit exceeded'
	},
	[ERROR_CODES.CORS_ERROR]: {
		vi: 'Lỗi CORS',
		en: 'CORS error'
	}
};

const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	INTERNAL_SERVER_ERROR: 500,
	BAD_GATEWAY: 502,
	SERVICE_UNAVAILABLE: 503
};

const ERROR_CODE_TO_HTTP_STATUS = {
	[ERROR_CODES.VALIDATION_ERROR]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[ERROR_CODES.NOT_FOUND]: HTTP_STATUS.NOT_FOUND,
	[ERROR_CODES.UNAUTHORIZED]: HTTP_STATUS.UNAUTHORIZED,
	[ERROR_CODES.FORBIDDEN]: HTTP_STATUS.FORBIDDEN,
	[ERROR_CODES.CONFLICT]: HTTP_STATUS.CONFLICT,
	[ERROR_CODES.DATABASE_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
	[ERROR_CODES.EXTERNAL_SERVICE_ERROR]: HTTP_STATUS.BAD_GATEWAY,
	[ERROR_CODES.INTERNAL_SERVER_ERROR]: HTTP_STATUS.INTERNAL_SERVER_ERROR,
	[ERROR_CODES.BAD_REQUEST]: HTTP_STATUS.BAD_REQUEST,
	[ERROR_CODES.PAYMENT_ERROR]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[ERROR_CODES.FILE_UPLOAD_ERROR]: HTTP_STATUS.BAD_REQUEST,
	[ERROR_CODES.PRODUCT_UNAVAILABLE]: HTTP_STATUS.CONFLICT,
	[ERROR_CODES.ORDER_PROCESSING_ERROR]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[ERROR_CODES.COMBO_ERROR]: HTTP_STATUS.UNPROCESSABLE_ENTITY,
	[ERROR_CODES.AUTH_ERROR]: HTTP_STATUS.UNAUTHORIZED,
	[ERROR_CODES.RATE_LIMIT_ERROR]: HTTP_STATUS.TOO_MANY_REQUESTS,
	[ERROR_CODES.CORS_ERROR]: HTTP_STATUS.FORBIDDEN
};

module.exports = {
	ERROR_CODES,
	ERROR_MESSAGES,
	HTTP_STATUS,
	ERROR_CODE_TO_HTTP_STATUS
};
